# Generated by Django 5.0.4 on 2024-05-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendDev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('skills', models.CharField(max_length=255)),
                ('experience', models.IntegerField()),
            ],
            options={
                'db_table': 'FrontendDev',
            },
        ),
    ]
